Running numpy/scripts/m1.py
[[START OF OUTPUT]]
[[1. 0.]
 [0. 1.]]
[1. 1. 1.]
[[END OF OUTPUT]]
Running numpy/scripts/m2.py
```
[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[2 2 2]
[[2 2 2]
 [2 2 2]]
[3 4 5]
```
Running numpy/scripts/m3.py
<bound method Device.__str__ of <module 'numpy.core._multiarray_umath' from '/path/to/numpy/core/_multiarray_umath.cpython-310-darwin.so'>>
Running numpy/scripts/m4.py
AttributeError: module 'numpy' has no attribute 'unique_counts'
Running numpy/scripts/m5.py
<class 'numpy.ndarray'>
--------------------------------
Running sklearn/scripts/m1.py
[[START OF OUTPUT]]
[[START OF FILE]]
Hello from sklearn!
[[END OF FILE]]
[[END OF OUTPUT]]
Running sklearn/scripts/m2.py
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
Running sklearn/scripts/m3.py
(150, 4)
(65, 4)
(150,)
(65,)
Running sklearn/scripts/m4.py
0.9333333333333333
Running sklearn/scripts/m5.py
Traceback (most recent call last):
  File "sklearn/scripts/m5.py", line 14, in main
    print(clf.score(None, y_test))
TypeError: score() missing 1 required positional argument: 'X'
--------------------------------
Running sql/scripts/m1.py
Hello from sql!
[]
Running sql/scripts/m2.py
Hello from sql!
[('Star Wars', 1977, 8.6), ('The Empire Strikes Back', 1980, 8.7), ('Return of the Jedi', 1983, 8.3)]
Running sql/scripts/m3.py
Hello from sql!
[('Return of the Jedi', 1983, 8.3)]
Running sql/scripts/m4.py
Hello from sql!
[('Return of the Jedi', 1983, 9.0)]
Running sql/scripts/m5.py
Hello from sql!
[('Star Wars', 1977, 8.6, None), ('The Empire Strikes Back', 1980, 8.7, None), ('Return of the Jedi', 1983, 8.3, None), ('The Dark Knight', 2008, 9.0, 'Christopher Nolan')]
--------------------------------
Running restapi/scripts/m1.py
zsh: command not found: uv
Running restapi/scripts/m2.py
zsh: command not found: uv
Running restapi/scripts/m3.py
uvicorn: command not found
Running restapi/scripts/m4.py
zsh: command not found: uv
Running restapi/scripts/m5.py
zsh: command not found: uv
